# Generated by Django 5.2.1 on 2025-05-31 18:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyType', models.CharField(choices=[('land', 'Land'), ('station', 'Station')], max_length=20)),
                ('locationRegion', models.CharField(max_length=100)),
                ('locationDistrict', models.CharField(max_length=100)),
                ('locationRoad', models.CharField(max_length=100)),
                ('landSize', models.CharField(blank=True, max_length=100, null=True)),
                ('landValue', models.CharField(blank=True, max_length=100, null=True)),
                ('stationType', models.CharField(blank=True, choices=[('fuel', 'Fuel'), ('lpg', 'LPG'), ('crm', 'CRM'), ('premix', 'Premix')], max_length=20, null=True)),
                ('stationCurrentOMC', models.CharField(blank=True, max_length=100, null=True)),
                ('stationDebtWithOMC', models.CharField(blank=True, max_length=100, null=True)),
                ('stationTankCapacityDiesel', models.CharField(blank=True, max_length=100, null=True)),
                ('stationTankCapacitySuper', models.CharField(blank=True, max_length=100, null=True)),
                ('projectedVolume', models.CharField(max_length=100)),
                ('leaseYears', models.CharField(max_length=100)),
                ('leaseRemaining', models.CharField(max_length=100)),
                ('loadingLocation', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=20)),
                ('reason', models.TextField()),
                ('originator', models.CharField(max_length=100)),
                ('distributionManager', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('civilWorksEstimatedCost', models.CharField(max_length=100)),
                ('civilWorksForecourtRequired', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksForecourtComment', models.CharField(blank=True, max_length=255, null=True)),
                ('civilWorksBuildingRequired', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksBuildingComment', models.CharField(blank=True, max_length=255, null=True)),
                ('civilWorksCanopyRequired', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksCanopyComment', models.CharField(blank=True, max_length=255, null=True)),
                ('civilWorksTankFarmRequired', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksTankFarmComment', models.CharField(blank=True, max_length=255, null=True)),
                ('civilWorksElectricalsRequired', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksElectricalsComment', models.CharField(blank=True, max_length=255, null=True)),
                ('civilWorksInterceptorStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksInterceptorFunctional', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksVentsStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksVentsFunctional', models.CharField(blank=True, max_length=100, null=True)),
                ('civilWorksOtherWorks', models.TextField(blank=True, null=True)),
                ('logistics', models.JSONField(default=list)),
                ('totalEstimatedCost', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
