# Generated by Django 5.2.1 on 2025-07-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landacquisition', '0003_landacquisition_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landacquisition',
            name='decision',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='landacquisition',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
