# Generated by Django 5.2.1 on 2025-07-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landacquisition', '0004_alter_landacquisition_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landacquisition',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landacquisition',
            name='loadingLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landacquisition',
            name='projectedVolume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
