# Generated by Django 5.2.1 on 2025-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='requester',
            field=models.CharField(choices=[('Exploration', 'Exploration'), ('Drilling Operations', 'Drilling Operations'), ('Production Operations', 'Production Operations'), ('Reservoir Engineering', 'Reservoir Engineering'), ('Health, Safety & Environment (HSE)', 'Health, Safety & Environment (HSE)'), ('Maintenance & Reliability', 'Maintenance & Reliability'), ('Project Management', 'Project Management'), ('Process Engineering', 'Process Engineering'), ('Subsurface Engineering', 'Subsurface Engineering'), ('Facilities Engineering', 'Facilities Engineering'), ('Logistics & Supply Chain', 'Logistics & Supply Chain'), ('Quality Assurance/Quality Control', 'Quality Assurance/Quality Control'), ('Instrumentation & Control', 'Instrumentation & Control'), ('Pipeline Operations', 'Pipeline Operations'), ('Refining Operations', 'Refining Operations'), ('Technical Support', 'Technical Support'), ('Field Operations', 'Field Operations'), ('Geosciences', 'Geosciences'), ('Well Services', 'Well Services'), ('Commissioning & Start-up', 'Commissioning & Start-up')], max_length=100),
        ),
    ]
