# Generated by Django 5.2.1 on 2025-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_alter_workorder_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='requester',
            field=models.CharField(choices=[('exploration', 'Exploration'), ('drilling', 'Drilling Operations'), ('production', 'Production Operations'), ('reservoir', 'Reservoir Engineering'), ('hse', 'Health, Safety & Environment (HSE)'), ('maintenance', 'Maintenance & Reliability'), ('project', 'Project Management'), ('process', 'Process Engineering'), ('subsurface', 'Subsurface Engineering'), ('facilities', 'Facilities Engineering'), ('logistics', 'Logistics & Supply Chain'), ('qa_qc', 'Quality Assurance/Quality Control'), ('ic', 'Instrumentation & Control'), ('pipeline', 'Pipeline Operations'), ('refining', 'Refining Operations'), ('tech_support', 'Technical Support'), ('field_ops', 'Field Operations'), ('geosciences', 'Geosciences'), ('well_services', 'Well Services'), ('commissioning', 'Commissioning & Start-up')], max_length=100),
        ),
    ]
