# Generated by Django 5.2.1 on 2025-07-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_alter_workorder_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indicates if the work order has been approved', verbose_name='Approval Status'),
        ),
    ]
